version: "2"

services:

  web:
    image: nginx:1.13
    environment:
      - VIRTUAL_PORT=80
    env_file: .env
    volumes:
      - ./public:/var/www/html
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build: docker/app
    env_file: .env
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "80"

  database:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: